### ISSUE TITLE
При перевороте экрана пересоздается игровое активити

### ISSUE THREAD

**Issue by MaximZemskov** [TheBestTeamEver/AndroidGame#5]

**Comment by Ztaz** [comment]
Предлагаю засунуть игровой контент во фрагмент

**Comment by MaximZemskov** [comment]
@Ztaz там вроде все в одну строчку в манифесте решается

**Comment by Ztaz** [comment]
По тз наше приложение должно поддерживать оба вида ориентации.

**Comment by MaximZemskov** [comment]
@Ztaz закрыто.
